// Exportaciones de componentes de estadísticas para personal
export { default as AsistenciasTotalesCard } from './AsistenciasTotalesCard';
export { default as PuntualidadCard } from './PuntualidadCard';
export { default as AusenciasCard } from './AusenciasCard';
export { default as AreasCard } from './AreasCard';
export { default as PersonalCard } from './PersonalCard';
export { default as PanelSeleccionEstadisticas } from './PanelSeleccionEstadisticas';
export { default as CalendarioAsistencias } from './CalendarioAsistencias';
export { default as ModalPersonalDetalle } from './ModalPersonalDetalle';
